import {motion} from 'framer-motion';import {Search,Inbox,LogOut,Menu,X,ChevronRight,Plus,Trash2,ExternalLink,CheckCircle2} from 'lucide-react';import {useState} from 'react';import {useAuth} from '../context/AuthContext';
export const Button=({children,className='',variant='primary',...p})=><button className={`px-4 py-2 rounded-xl text-sm font-semibold transition border ${variant==='primary'?'bg-cyan-400/15 border-cyan-300/30 text-cyan-100 hover:bg-cyan-400/25':'bg-white/5 border-white/10 text-slate-200 hover:bg-white/10'} ${className}`} {...p}>{children}</button>;
export const Card=({children,className=''})=><div className={`rounded-2xl border border-white/10 bg-white/[.045] backdrop-blur-xl shadow-neon ${className}`}>{children}</div>;
export const Stat=({label,value,icon:Icon})=><Card className="p-5"><div className="flex items-center justify-between"><div><div className="text-xs uppercase tracking-wider text-slate-400">{label}</div><div className="mt-2 text-3xl font-bold text-white">{value}</div></div>{Icon&&<div className="rounded-xl bg-cyan-400/10 p-3 text-cyan-300"><Icon size={22}/></div>}</div></Card>;
export const Empty=({text='Nothing here yet.'})=><div className="py-16 text-center text-slate-500">{text}</div>;
export const Loader=()=> <div className="animate-pulse rounded-2xl border border-white/10 bg-white/5 h-32"/>;
export function Topbar({onMenu}){const {user,logout}=useAuth();const [open,setOpen]=useState(false);return <header className="sticky top-0 z-30 border-b border-white/10 bg-[#050816]/80 backdrop-blur-xl"><div className="flex h-16 items-center justify-between px-4 md:px-6"><button className="md:hidden text-slate-300" onClick={onMenu}><Menu/></button><div><div className="font-bold text-white">AI<span className="text-cyan-300">×</span>ROBOTICS</div><div className="text-[10px] uppercase tracking-[.3em] text-slate-500">Learning Command Center</div></div><div className="relative"><button onClick={()=>setOpen(!open)} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/5 px-3 py-2"><div className="hidden sm:block text-right"><div className="text-sm font-medium text-white">{user?.name}</div><div className="text-xs text-cyan-300">{user?.role}</div></div><div className="h-8 w-8 rounded-full bg-gradient-to-br from-cyan-400/30 to-violet-400/30 grid place-items-center">{user?.name?.[0]}</div></button>{open&&<div className="absolute right-0 mt-2 w-44 rounded-xl border border-white/10 bg-[#0b1022] p-2 shadow-2xl"><button onClick={logout} className="w-full flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-300 hover:bg-white/5"><LogOut size={16}/> Logout</button></div>}</div></div></header>}
export function Sidebar({open,onClose,items}){return <aside className={`fixed md:static z-40 inset-y-0 left-0 w-64 border-r border-white/10 bg-[#070b18]/95 backdrop-blur-xl transition-transform ${open?'translate-x-0':'-translate-x-full md:translate-x-0'}`}><div className="flex h-16 items-center justify-between px-5 border-b border-white/10"><div className="text-sm font-bold text-slate-200">NAVIGATION</div><button className="md:hidden" onClick={onClose}><X/></button></div><nav className="p-3 space-y-1">{items.map(({label,to,icon:Icon})=><a key={to} href={to} onClick={onClose} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm text-slate-400 hover:bg-cyan-400/10 hover:text-cyan-200"><Icon size={18}/>{label}</a>)}</nav></aside>}
export function Layout({children,items}){const [open,setOpen]=useState(false);return <div className="min-h-screen"><Topbar onMenu={()=>setOpen(true)}/><div className="flex min-h-[calc(100vh-4rem)]"><Sidebar open={open} onClose={()=>setOpen(false)} items={items}/><main className="min-w-0 flex-1 p-4 md:p-7">{children}</main></div></div>}
export const PageTitle=({eyebrow,title,description,action})=><div className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="text-xs uppercase tracking-[.3em] text-cyan-300">{eyebrow}</div><h1 className="mt-1 text-3xl md:text-4xl font-black text-white">{title}</h1>{description&&<p className="mt-2 text-sm text-slate-400">{description}</p>}</div>{action}</div>;
export function SearchFilter({search,setSearch,subject,setSubject}){return <div className="flex flex-col sm:flex-row gap-3 mb-5"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-500" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..." className="w-full rounded-xl border border-white/10 bg-white/5 px-10 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40"/></div><select value={subject} onChange={e=>setSubject(e.target.value)} className="rounded-xl border border-white/10 bg-[#0b1022] px-3 text-sm text-slate-200"><option value="">All subjects</option><option>AI</option><option>Robotics</option></select></div>}
export function Modal({open,onClose,title,children}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="w-full max-w-2xl max-h-[90vh] overflow-auto rounded-2xl border border-white/10 bg-[#0a1021] p-5"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold text-white">{title}</h2><button onClick={onClose}><X/></button></div>{children}</motion.div></div>}
export const Field=({label,...p})=><label className="block"><span className="mb-1 block text-xs text-slate-400">{label}</span><input className="w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40" {...p}/></label>;
export const TextArea=({label,...p})=><label className="block"><span className="mb-1 block text-xs text-slate-400">{label}</span><textarea className="min-h-24 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/40" {...p}/></label>;
export {Search,Inbox,Plus,Trash2,ExternalLink,CheckCircle2,ChevronRight};
