const Content=require('../models/Content');const User=require('../models/User');const {notifyTarget}=require('../services/notify');
function visibilityForStudent(u){return {$or:[{visibility:'ALL'},{visibility:'CLASS',class:u.class},{visibility:'SECTION',class:u.class,section:u.section}]}}
async function list(req,res){const q={};if(req.query.subject)q.subject=req.query.subject;if(req.query.type)q.type=req.query.type;if(req.query.class)q.class=Number(req.query.class);if(req.query.section)q.section=req.query.section.toUpperCase();if(req.query.topic)q.topic={$regex:req.query.topic,$options:'i'};if(req.query.search)q.$or=[{title:{$regex:req.query.search,$options:'i'}},{description:{$regex:req.query.search,$options:'i'}}];if(req.user.role==='STUDENT')Object.assign(q,visibilityForStudent(req.user));res.json({items:await Content.find(q).populate('uploadedBy','name role').sort({createdAt:-1})})}
async function get(req,res){const item=await Content.findById(req.params.id).populate('uploadedBy','name');if(!item)return res.status(404).json({message:'Content not found'});if(req.user.role==='STUDENT'&&!((item.visibility==='ALL')||(item.visibility==='CLASS'&&item.class===req.user.class)||(item.visibility==='SECTION'&&item.class===req.user.class&&item.section===req.user.section)))return res.status(403).json({message:'Content is not available to you'});res.json({item})}
async function create(req,res){const b=req.body;if(!b.title||!b.type||!b.subject)return res.status(400).json({message:'Title, type and subject are required'});const item=await Content.create({...b,class:b.class?Number(b.class):undefined,section:b.section?b.section.toUpperCase():undefined,uploadedBy:req.user._id});await notifyTarget({title:'New learning resource',message:b.title,type:'CONTENT',relatedId:item._id,target:b.visibility||'ALL',classNumber:b.class,section:b.section});res.status(201).json({item})}
async function update(req,res){const item=await Content.findByIdAndUpdate(req.params.id,{...req.body,updatedAt:new Date()},{new:true});if(!item)return res.status(404).json({message:'Content not found'});res.json({item})}
async function remove(req,res){await Content.findByIdAndDelete(req.params.id);res.json({message:'Content deleted'})}
async function stats(req,res){const [total,videos,resources,ai,robotics]=await Promise.all([Content.countDocuments(),Content.countDocuments({type:'VIDEO'}),Content.countDocuments({type:{$ne:'VIDEO'}}),Content.countDocuments({subject:'AI'}),Content.countDocuments({subject:'Robotics'})]);res.json({total,videos,resources,ai,robotics})}
module.exports={list,get,create,update,remove,stats};
